(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Text = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CC3399").s().p("AiMCpIAAgMQAVgCAIgKQAHgKAAgrIAAi1QAAgcgCgIQgEgKgGgEQgIgFgQgBIAAgNICGAAIAABKQAggzAYgQQAZgRAXAAQAUAAALAMQAMAMAAAWQAAAYgLANQgMANgQAAQgTAAgNgMIgQgOQgEgCgEAAQgLAAgJAIQgOAMgIAWQgKAiAAAoIAABMIAAAUQABAUACAFQADAKAJAEQAHAFAVABIAAAMg");
	this.shape.setTransform(348.6,49.225);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CC3399").s().p("AhqB2QgeguAAhDQAAhRAsgwQAsgxA7AAQAyAAAlApQAlApACBQIizAAQADBBAgAlQAXAeAiAAQAVAAASgMQARgMATgeIAMAHQgaA3ghAXQggAWgqAAQhJAAglg4gAgXiFQgVAgAAA2IAAANIBfAAQAAg5gGgVQgGgVgNgLQgIgGgMAAQgRAAgMARg");
	this.shape_1.setTransform(316.425,49.725);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CC3399").s().p("AgiDSQgWgSgGgVQgEgMAAg1IAAixIgqAAIAAgMQAsgfAfgjQAfgiAWgrIALAAIAAB5IBPAAIAAAiIhPAAIAADKQAAAdAEAIQACAIAHAFQAGAFAGAAQAXAAAUgiIALAHQgdBEg/AAQgfAAgVgRg");
	this.shape_2.setTransform(288.2,43.925);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CC3399").s().p("AgjDSQgWgSgFgVQgEgMABg1IAAixIgrAAIAAgMQArgfAggjQAfgiAWgrIAMAAIAAB5IBNAAIAAAiIhNAAIAADKQAAAdADAIQACAIAHAFQAGAFAGAAQAXAAAUgiIAKAHQgbBEhBAAQgeAAgWgRg");
	this.shape_3.setTransform(264.2,43.925);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#CC3399").s().p("AhqB2QgeguAAhDQAAhRAsgwQAsgxA7AAQAyAAAlApQAlApACBQIizAAQADBBAgAlQAXAeAiAAQAVAAASgMQARgMATgeIAMAHQgaA3ghAXQggAWgqAAQhJAAglg4gAgXiFQgVAgAAA2IAAANIBfAAQAAg5gGgVQgGgVgNgLQgIgGgMAAQgRAAgMARg");
	this.shape_4.setTransform(236.475,49.725);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#CC3399").s().p("AjbDuIAAgNIAPAAQAVAAAMgHQAJgFAGgMQADgIAAgkIAAk5QAAgkgDgKQgEgJgMgGQgMgHgUAAIgPAAIAAgNID9AAIAAANIgVAAQgUAAgMAHQgKAFgFAMQgEAIAAAkIAAEvQAAAkAEALQAFAJAMAFQAIAEAiAAIAnAAQAmAAAZgOQAagNASgdQASgdARg4IAPAAIgSCng");
	this.shape_5.setTransform(195.35,42.325);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#CC3399").s().p("AhqB2QgeguAAhDQAAhRAsgwQAsgxA7AAQAyAAAlApQAlApACBQIizAAQADBBAgAlQAXAeAiAAQAVAAASgMQARgMATgeIAMAHQgaA3ghAXQggAWgqAAQhJAAglg4gAgXiFQgVAgAAA2IAAANIBfAAQAAg5gGgVQgGgVgNgLQgIgGgMAAQgRAAgMARg");
	this.shape_6.setTransform(138.525,49.725);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#CC3399").s().p("AgHCpIhuj+QgUgugMgMQgHgJgQgDIAAgNICtAAIAAANQgPAAgGAGQgIAHAAALQAAANAPAkIA1B6IArhpQATguAAgTQAAgLgIgHQgIgHgUAAIAAgNIBrAAIAAANQgPACgJAJQgLAKgTAuIhuEBg");
	this.shape_7.setTransform(104,50.225);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#CC3399").s().p("AhxB6Qgog0AAhFQAAhFApg1QApg0BHAAQAqAAAlAWQAlAWATApQATApAAAvQAABGgjAvQgrA5hMAAQhJAAgog0gAgdiHQgNAOgEAoQgEAoAABGQAAAlAFAhQAEAZAMANQANANAQAAQAPAAAKgJQAOgMAFgVQAHgiAAhkQAAg8gHgWQgHgXgNgKQgJgHgPAAQgQAAgNANg");
	this.shape_8.setTransform(68.025,49.725);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#CC3399").s().p("AjcDuIAAgNIAQAAQAVAAANgHQAIgFAFgMQAFgIAAgkIAAk5QAAgkgFgKQgDgJgMgGQgMgHgUAAIgQAAIAAgNID9AAIAAANIgUAAQgUAAgNAHQgIAFgGAMQgEAIAAAkIAAEvQAAAkAFALQADAJANAFQAJAEAgAAIAoAAQAmAAAagOQAYgNAUgdQARgdARg4IAOAAIgSCng");
	this.shape_9.setTransform(25.4,42.325);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,366,83.7);


(lib.Letter = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(3,1,1).p("AUjpSIAASvMgpFAAAQFYj6iJn4QgriehWikIhIh7MAo/AAAIt2DyA0ipSIAGAAA0ipcIAGAKIO6D6");
	this.shape.setTransform(131.475,60.475);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1.5,-1.5,266,124);


(lib.Tween4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Letter("synched",0);
	this.instance.setTransform(-0.05,0.05,1,1,0,0,0,131.4,60.5);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AApDmIgEgBIgEgBIgDgCIgDgCIgDgCIgFgGIgCgEIgBgDIgBgEIgGgFIgJgFIgHgFIgJgEIgIgFIgKgGIgEgDIgFgBIgJgBIgEgBIgEgBIgEgBIgIgEIgDgCIgDgDIgGgGIgDgEIgEgBIgDgCIgDgCIgDgCIAAAAQgKgBgKgEIgJgEIgIgFIgIgEIgHgFIgGgFIgFgEIgHgDIgIgFIgKgFIgJgEIgJgFIgIgEIgEgCIgEgDIgDgDIgEgDIgHgBIgFAAIgGgBIgFgBIgEgBIgEgCIgEgCIgEgCIgIgBIgFgBIgEgBIgEgBIgEgCIgDgDIgDgCIgDgEIgDgEIgCgDIgCgEIgCgFIgBgEIgBgEIgBgFIgDgGIgDgFIgDgFIgDgCIgEgBIgEgCIgHgGIgEgEIgDgDIgDgEIgDgEIgDgEIgCgEIgBgFIgBgFIgFgCIgEgEIgDgDIgEgHIgCgEIgCgEIgEgIIgCgDIgCgFQgDgJgBgJIgBgMIAAgHIAAgFIAAgIIAAgKIAAgFIABgEIADgJIACgEIACgEIACgEIADgEIADgEIADgEIAEgDIAEgFIADgEIAEgDIACgDIAEgEIADgDQAWgKAYgFQAZgFAZAAIBAAAQAZAAAYACQAMABALAGIAFABIAIABIAEAAIAEABIAEABIAEABIAEACIADACIAEADIAFAHIADAEIACAEIADAEIACAEIAHAEIAEACIAEADIAEACIADADIADACIADADIAEAHIABADIACAEIABAEIABAFIACAFIABAFIABAFIABABIAEACIADACIAEACIADADIADAEIACAEIAFgHIADgCIAEgDIAEgDIAFgDIAEgDIAFgDIADgEIACgEIADgDIAEgDIAEgCIAEgCIAEgCIADgBQAIgCAJgBIALAAIAOAAIAKAAIALAAIALgBQAhgIAhgBIBDAAIBJABQAhAAAQAdIAGAMIACAEQAFAVgBAVIAAAgQAAAUgCATQgCAWgPARQgHAHgHAFIgJALIgEADIgDACIgFADIgEACIgFACIgFACIgDADIgEACQgGAEgIABIgKACIgMABIgJAAIgDAAIgCABIgDADIgCACIgGAFIgDACIgFACIgJADIgEABIgFAAIgFABIgEAAIgHAEIgEACIgEABQgMADgNAAIgXABIgVAAIgUAAIgRAAIgIAEIgFACIgEABIgEABIgEAAIgEABIgDADIAAADQACAGAAAGIABAJIAAAIIABALIAAAMIAAAGIgBAEIAAADIAAAFIABAEIgBAEIAAAEIgCAEIgBADIgDADIgCADIgDADIgDACIgEACIgDABIgEABIgEAAIgEAAg");
	this.shape.setTransform(4.0273,-22.5021);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-132.9,-61.9,265.9,123.9);


(lib.Tween3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Letter("synched",0);
	this.instance.setTransform(-0.05,0.05,1,1,0,0,0,131.4,60.5);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AApDmIgEgBIgEgBIgDgCIgDgCIgDgCIgFgGIgCgEIgBgDIgBgEIgGgFIgJgFIgHgFIgJgEIgIgFIgKgGIgEgDIgFgBIgJgBIgEgBIgEgBIgEgBIgIgEIgDgCIgDgDIgGgGIgDgEIgEgBIgDgCIgDgCIgDgCIAAAAQgKgBgKgEIgJgEIgIgFIgIgEIgHgFIgGgFIgFgEIgHgDIgIgFIgKgFIgJgEIgJgFIgIgEIgEgCIgEgDIgDgDIgEgDIgHgBIgFAAIgGgBIgFgBIgEgBIgEgCIgEgCIgEgCIgIgBIgFgBIgEgBIgEgBIgEgCIgDgDIgDgCIgDgEIgDgEIgCgDIgCgEIgCgFIgBgEIgBgEIgBgFIgDgGIgDgFIgDgFIgDgCIgEgBIgEgCIgHgGIgEgEIgDgDIgDgEIgDgEIgDgEIgCgEIgBgFIgBgFIgFgCIgEgEIgDgDIgEgHIgCgEIgCgEIgEgIIgCgDIgCgFQgDgJgBgJIgBgMIAAgHIAAgFIAAgIIAAgKIAAgFIABgEIADgJIACgEIACgEIACgEIADgEIADgEIADgEIAEgDIAEgFIADgEIAEgDIACgDIAEgEIADgDQAWgKAYgFQAZgFAZAAIBAAAQAZAAAYACQAMABALAGIAFABIAIABIAEAAIAEABIAEABIAEABIAEACIADACIAEADIAFAHIADAEIACAEIADAEIACAEIAHAEIAEACIAEADIAEACIADADIADACIADADIAEAHIABADIACAEIABAEIABAFIACAFIABAFIABAFIABABIAEACIADACIAEACIADADIADAEIACAEIAFgHIADgCIAEgDIAEgDIAFgDIAEgDIAFgDIADgEIACgEIADgDIAEgDIAEgCIAEgCIAEgCIADgBQAIgCAJgBIALAAIAOAAIAKAAIALAAIALgBQAhgIAhgBIBDAAIBJABQAhAAAQAdIAGAMIACAEQAFAVgBAVIAAAgQAAAUgCATQgCAWgPARQgHAHgHAFIgJALIgEADIgDACIgFADIgEACIgFACIgFACIgDADIgEACQgGAEgIABIgKACIgMABIgJAAIgDAAIgCABIgDADIgCACIgGAFIgDACIgFACIgJADIgEABIgFAAIgFABIgEAAIgHAEIgEACIgEABQgMADgNAAIgXABIgVAAIgUAAIgRAAIgIAEIgFACIgEABIgEABIgEAAIgEABIgDADIAAADQACAGAAAGIABAJIAAAIIABALIAAAMIAAAGIgBAEIAAADIAAAFIABAEIgBAEIAAAEIgCAEIgBADIgDADIgCADIgDADIgDACIgEACIgDABIgEABIgEAAIgEAAg");
	this.shape.setTransform(4.0273,-22.5021);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-132.9,-61.9,265.9,123.9);


// stage content:
(lib.Untitled1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Text
	this.instance = new lib.Text("synched",0);
	this.instance.setTransform(219.95,271.4,1,1,0,0,0,183,41.9);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("EgkyAZFIgIgDIgEgEIgEgEIgDgFIgCgFIgCgIIACgIIADgHIADgFIAEgEIAFgDIAGgCIAIgCIAHgDIAHgDIAIgCIAIgBIAHAAIAIgBIAEgBIAGgCIAFgDIAPgCIAHgCIAHgCIAHgCIAIgCIANgDIAGAAIAAgBIAEgFIAFgFIAGgEIAGgCIAHgCIAHAAIAHgBIAHAAIAGgBIAHAAIAEgBIAEgCIAIgDIAHgDIAIgEIAHgEIAHgCIAOgJIAOgKIAHgFIAHgFIAHgFIAHgFIAHgDIAHgEIAIgEIAHgEIAHgIIAJgKIAFgEIAGgFIAGgEIAPgJIAGgGIAGgHIAGgEIAGgEIAFgEIAEgEIAJgOIAJgOIAEgHIAFgHIAKgNIAFgGIAMgIIAMgIIAGgEIAGgEIANgHIAPgIIAOgQIAJgLIALgJIAVgPIAPgJIADgEIAEgDIAGgFIAGgEIARgQIARgRIAQgPIARgPIAMgMIAFgHIAEgIIAEgHIADgIIAEgHIAEgGIAFgFIAFgFIAGgFIAFgGIAGgFIAFgGIAGgGIADgFIADgGIADgGIADgGIAFgGIAEgGIAGgHIAGgHIAAgBIACgHIABgHIACgHIACgHIACgGIADgHIADgGQAGgKAIgJIALgLIAKgLIAJgLIAIgKIADgGIACgIIADgHIACgHQAFgJAHgJIAOgRIAQgUQAHgKAJgIIALgJIAGgFIAHgIIAJgJIAGgFIAFgEIAGgFIALgKIAEgHIAEgGIAHgGIAGgGIADgEIABgGIABgGIACgIIAEgHIADgGIAFgHIAEgGIAGgGIAFgGIACgNIADgQIACgIIADgIIACgHIAFgNIAEgFIAEgGIAEgEIADgFIADgFIADgIIADgIIADgIIADgHIADgHIADgHIADgHIACgHIACgHQAAgOACgNIADgPIAFgQQAEgMAGgLIADgHIADgIIACgHIACgIQABgPAEgPQADgJAAgJIABAAIgBAAIABgEIABghQgBgNACgNIADgQIAEgHIACgEIADgFIADgFIADgHIACgHIAAgFIABgIIABgHIADgHIAEgHIAEgIIAEgIIAEgHIAEgIIABgHIACgHIABgHIABgGIABgGIABgIIADgHIADgHIANgSQAHgJAEgKIAKgUQAFgJAGgIIALgMIAGgHIADgGIAEgGIACgHIACgIIACgIIADgGIAEgHIAFgGIADgFIADgFQAHgYAKgWIARghQAJgQANgNQATgTASgUIARgSIADgHIADgGIAEgFQALgLANgKIAVgRIAYgUIATgPIAUgOIAFgGIAFgGIAFgGIAFgFIAFgEIAFgEIAGgEIAGgIIAJgMIAFgGIAEgGIAFgFIAKgKIAEgFIADgGIADgGIADgFQALgOANgNIAYgYIAWgWQAKgLAJgMQAJgMAKgJIAGgFIAFgEIAHgCIAGgDIAHgBIAEgDIACgBIAAgBIADgGIADgGIAEgGIAGgEIAFgFIAFgFIAEgFIAGgHIAGgGIAFgHIAVgQIASgOIAWgSIASgLIAUgMIAGgFIAFgEIAGgFIAFgFIAEgDIAFgEIAFgEQAMgNAOgLQAJgHAKgGQAOgJAQgFIAYgJIAIgCIAIgFIAHgEIAGgDIAGgCIAGgCIAegTIAWgOQAOgHAPgFQAMgDAMgBIAIgBIAGgEIAGgDIAGgEIAHgCIAGgDIAIgCIAIgBIAHAAIAJAAIAHgBIAHAAIAIgCIAHgDIAIgBIAIgBIAIgBIAJgBIAIAAIAEgIIAEgIIAEgJIAGgOIAGgPIAIgQIAHgQIAIgPIAEgGIAegZIAYgUQAOgKAOgJQAOgJAQgHIAXgKIAGgEIAHgEQAXgVAVgZQATgWAWgSIAwgtQAcgaAggXIAHgFIAZgZQAMgOAQgIQAMgGAMgIIAagSQAUgMAWgGIAIgBIAHgBIAHgBIAHAAIAIgBIAEgBQBEgtBNgWQBXgaBYgTQA4gMA5gGQBGgHBEgQQAegHAfABIAQAAIAbgHIARgGIAOgDQALgDAMAAIARgBQBygOBzACQAWAAAVgBQBmgIBmABQBvABBvAAQBqgBBqAEIARACIAGACIAFADIAJAAIAMAAIAHAAIAIAAIAQABIAQABIAJABIAGACIAGADIAGAEIAGAEIAGAFIAGAEIAGAEIAHABIACAAIAGABIAFACIAFACIAFAEIAEAFIACAFIACAFIABAGIgBAGIgCAGIgCAFIgEAEIgFAEIgFADIgFACIgGAAIgQgCIgNgDIgGgDIgHgDIgMgIIgMgKIgBAAIgCAAIgBAAIABAAIgGAAIgQgBIgIAAIgIAAIgLAAIgNgBIgHAAIgHgCIgHgDIgEgCQhtgDhtAAQh1ABh1gBQhbgBhbAIQhXAIhZgDQgYgBgZABIgRADIgRADIgHABIgIABIgQABIgHAAIgfAIIgYAHQgRAFgRAAIgbAAIgYABQhJAThLAHQhVAHhSAaQg/AUhBASQg6ARg0AhQgKAGgKADIgHABIgIABIgIABIgHAAIgIABIgHACQgKAFgKAGIgNAIIgNAJIgSALIgNAIIgGAEQgdAhgjAaQgiAagfAdQgjAfgdAjQgdAjgoATIgNAGQgPAGgNAJIgUANIgcAWIgOAMIgJAHIgCAEIgBABIAAAAIAAABIAAAAIAAABIAAAAIgBADIgDAGIgCAGIgDAGIgEAHIgDAGIgDAGIgCAHIgDAHIgDAGIBWAAIBUAAIBdABQArAAAqgCIAGgCIAGAAIAGgBIAFABIAGACIAGACIAGAEIAFACIAFADIAPABQALgBAKACIAXAEQALACAKAFIAMAHIAMAHIAGACIAGACQAKAAAJACIAOAEIAOAFIAVAKIANAJIAGAFIAGADIAHAEIAHADIAGADIAFADIAEAEIAFAFIAHADIAGAEIAHAEIAHADIAFAEIAFAEIAHADIAGADIAFAFIAFAGIAEAGIACAIIADAHIABAHIAAAPIAAAQIAAAJIgBAJIgBAPIgCAPIgCAFIgDAGIgMASIgJAOIgJAOQgHALgJAJIgGAGIgEAHIgFAHIgFAHIgEAGIgKAKIgKAKIgFAFIgFAEIgKAKIgMAJIgHADIgIADIgEADIgEACIgLAJIgMAJIgHADIgGADIgHADIgOAEQgRADgRAAIgXAAIgkAAIgSABIgJAAIgRADIgRADIgJABIgJABIgSAAQgxgKgxgGQgkgEglAAQg1AAg0gJQgvgIgkgdQgNgLgJgPIgDgGIgBgGIgCgGIgBgHIgCgGIAAgBIgHgDIgGgFIgFgFIgDgGIgDgGIgDgHIgBgHIAAgHIAAgnIAAgpIAAggIABggQAAgMADgMIAFgOIAGgOIADgHIACgIIADgIIACgJIgDAAIgCAAIgFACIgFABIgIADIgHABIgJABIgJAAIgJABIgJAAIgCABIgCAAIgCABIgDACIgFAEIgHAEIgHADIgHACIgHABIgHABIgHABIgHACIgGABIgHADIgVAMIgOAJIgMAIQgJAGgKAEIgMAFIgNAHIgNAFIgHADIgHADIgHACIgOAFIgGADIgGAEIgGADIgGAEIgGAFIgGAGIgFAGIgFAEIgFAFIgFAEIgGAEIgKAJIgLAJIgMAIIgOAJIgOAJIgHAEIgPAMIgNALIgGAFIgHAFIgGAEIgGAGIgFAFIgFAGIgEAFIgFAGIgEAEIgEAEIgEADIAAABIgDAFIgDAFIgEAGIgGAGIgGAEIgGAFIgGAEIgHADIgGACIgGABQgLAMgLAOIgQATIgXAXIgTASIgRATIgHANIgIAMIgEAFIgGAHIgMAMIgGAGIgEAGIgEAGIgFAGIgFAFIgFAFIgFAEIgCABIgBABIgBABIABgBIAAAAIgDACIgDADQgIANgMAJQgKAKgMAIIgbAUIgVARIgaAWIgCABIgCACIgDAIIgDAFIgEAFIgEAFIgEAEIgEAEIgFAFIgFAEIgFAFIgFAHIgGAGIgFAHIgFAGIgGAFIgFAGIgGAGIgHALIgGAMIgEAIIgDAIIgEAIIgEAIIgDAIIgCAHIgDAHIgDAIIgDAFIgDAGIgEAGIgEAGIgBAAIgBAHIgCAHIgCAHIgDAHIgDAHIgEAFIgFAHIgEAGIgHAHIgGAGIgHAOIgIANIgHAOIgHAMIgJAMIgEAHIgDAUIgDAOIgGAPQgEAMgGALIgIAOIgBAFIAAAFIgCAIIgCAIIgCAHIgDAIIgDAHIgDAEIgEAGQgCALAAAKIAAASIgBARIgDAXIgDAQIgBAHIgCALIgCAPIgCAHIgDAIIgHARIgIAQIgCAIIgDAJIgCAIIAAAOIgCAPIgDAOIgGAPIgGAOIgDAHIgEAMIgFAOIgDAGIgEAHIgFAHIgIAKIgBACIgBABIgCAIIgCAIIgCAIIgCAIIgCAIIAAAGIgBAFIgCAGIgDAHIgEAFIgEAGIgGAGIgFAGIgEAGIgBAGIgBAGIgCAHIgDAHIgEAGIgEAGIgFAGIgEAEIgEAFIgEAEIgEAGIgEAFIgFAFIgFAFIgFAEIgFAFIgFAEIgFAEIgFAEIgFAGIgFAGIgOALIgLALIgKALIgOASIgIALIgIALIgCAHIgCAIIgDAHQgFAKgHAIIgJAMIgKALIgPARIgKALIgCADIgDAJIgCAIIgBAGIgBAHIgCAGIgDAHIgEAGIgEAGIgFAHIgGAGIgFAGIgDAGIgCAFIgDAGIgEAGIgIALIgJAKIgFAFIgFAFIgFAFIgKAJQgGAPgIANQgJAPgNANIgVATIgdAcQgRAQgSAOIgEAEIgEAEIgGAEIgGAEIgGAEIgGADIgHAEIgHAFIgGAGIgGAGIgFAHIgFAFIgFAFIgFAGIgMAIIgNAIIgGADIgIAEIgOAJIgHAFIgEAEIgEADIgIAOIgIANIgEAGIgEAGIgJAMIgFAGIgGAFIgGAEIgHAFIgFAFIgFAFIgFAFIgGAEIgHAFIgIAFIgHAFIgEADIgDAEIgFAGIgFAGIgGAFIgGAFIgHAEIgHADIgHAEIgHADIgOAJIgNAJIgNAKIgNAIIgMAGIgHADIgEADIgFACIgFADIgGACIgFACIgGACIgIADIgHACIgIABIgHABIgHABIgHAAIgDAEIgDAEIgEACIgGADIgHADIgHACIgHABIgIABIgHABIgHACIgHADIgHACIgHABIgIABIgFABIgHADIgGACIgHACIgIABIgIABIgIAAIgBAAIgGADIgGADIgGABIgHACIgHABIgIgBgA+MWGIgBACIABgBIABgBgAzvJNIgBACIABgCIABgBIgBABgAy8DJIgBABIABgBIABgCIgBACgAy6DFIAAgBIAAgBIAAACgADmoUQAcACAcAHIAmAJIAFAAIAEAAIAFAAIAFAAIAFAAIAFgBIAFgBIAAAAIAZgEIAagCIAagBIAaAAIAbAAIAKAAIAFgBIAFgBIAEgCIAFgCIAEgCIAEgDIAEgDIAEgEIAEgDIAEgDIAEgCIADgDIAEgCIAEgBIADgCIAEgCIAEgBIAEgDIAEgEIADgDIAEgEIADgDIAGgGIAHgHIAGgGIADgEIADgEIACgFIADgEIADgEIAHgIIAHgIIADgDIAGgKIAHgJIAFgIIAFgJIAFgHIAEgFIAAgFIABgKIAAgFIAAgLIAAgLIAAgLIgEgCIgIgFIgHgFIgIgFIgJgEIgIgFIgGgFIgGgFIgFgCIgFgDIgEgCIgFgDIgEgCIgEgDIgEgCIgEgDIgDgDIgFgDIgEgCIgEgDIgFgCIgEgBIgFgCIgFgBIgFgCIgLgBIgJgBIgJgDIgJgDIgLgFIgIgFIgHgEIgEgCIgOgEIgOgCIgQgBIgNAAIgNgCIgNgGIgKgFQgmAFgmgBIhPgBIhWAAIhdAAIgvAAIgCALIgCAKIgDAKIgFAOIgFAPIgEAJIgCACIgBADIgBAFIAAACIgBAZIAAAbIAAAcIAAAbQAAANgBALQgBAJAFAFIADACIADACIADAEIADAEIADAEIACAFIACAEIADAFIACAGIABADIAAAEIABAEIABAGIAAAAIADAEIAEADIAEAEIAJAFIAJAFIAJAEIAKAEIAKACIAIACIgCAAIAEABIAxAFQAdADAcgBIAZgBIAgACgApwpQIgBABIABgBIABgBIABAAIAAAAIgCABgAhuuHIABAAIACgBIgCAAIgBABgAIN17IACAAIABAAIgBAAIgCAAg");
	this.shape.setTransform(330.225,181.4444);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance,p:{x:219.95,y:271.4}}]}).to({state:[]},1).to({state:[{t:this.shape},{t:this.instance,p:{x:192.95,y:392.4}}]},38).to({state:[{t:this.instance,p:{x:-234.05,y:438.2}}]},30).wait(21));

	// Letter
	this.instance_1 = new lib.Letter("synched",0);
	this.instance_1.setTransform(454.35,393.55,1,1,0,0,0,131.4,60.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AApDmIgEgBIgEgBIgDgCIgDgCIgDgCIgFgGIgCgEIgBgDIgBgEIgGgFIgJgFIgHgFIgJgEIgIgFIgKgGIgEgDIgFgBIgJgBIgEgBIgEgBIgEgBIgIgEIgDgCIgDgDIgGgGIgDgEIgEgBIgDgCIgDgCIgDgCIAAAAQgLgCgJgDIgJgEIgIgFIgIgEIgHgFIgGgFIgFgEIgHgDIgIgFIgKgFIgJgEIgJgFIgIgEIgEgCIgEgDIgDgDIgEgDIgHgBIgFAAIgGgBIgFgBIgEgBIgEgCIgEgCIgEgCIgIgBIgFgBIgEgBIgEgBIgEgCIgDgDIgDgCIgDgEIgDgEIgCgDIgCgEIgCgFIgBgEIgBgEIgBgFIgDgGIgDgFIgDgFIgDgCIgEgBIgEgCIgHgGIgEgEIgDgDIgDgEIgDgEIgDgEIgCgEIgBgFIgBgFIgFgCIgEgEIgDgDIgEgHIgCgEIgCgEIgEgIIgCgDIgCgFQgDgJgBgJIgBgMIAAgHIAAgFIAAgIIAAgKIAAgFIABgEIADgJIACgEIACgEIACgEIADgEIADgEIADgEIAEgDIAEgFIADgEIAEgDIACgDIAEgEIADgDQAWgKAYgFQAZgFAZAAIBAAAQAZAAAYACQAMABALAGIAFABIAIABIAEAAIAEABIAEABIAEABIAEACIADACIAEADIAFAHIADAEIACAEIADAEIACAEIAHAEIAEACIAEADIAEACIADADIADACIADADIAEAHIABADIACAEIABAEIABAFIACAFIABAFIABAFIABABIAEACIADACIAEACIADADIADAEIACAEIAFgHIADgCIAEgDIAEgDIAFgDIAEgDIAFgDIADgEIACgEIADgDIAEgDIAEgCIAEgCIAEgCIADgBQAIgCAJgBIALAAIAOAAIAKAAIALAAIALgBQAhgIAhgBIBDAAIBJABQAhAAAQAdIAGAMIACAEQAFAVgBAVIAAAgQAAAUgCATQgCAWgPARQgHAHgHAFIgJALIgEADIgDACIgFADIgEACIgFACIgFACIgDADIgEACQgGAEgIABIgKACIgMABIgJAAIgDAAIgCABIgDADIgCACIgGAFIgDACIgFACIgJADIgEABIgFAAIgFABIgEAAIgHAEIgEACIgEABQgMADgNAAIgXABIgVAAIgUAAIgRAAIgIAEIgFACIgEABIgEABIgEAAIgEABIgDADIAAADQACAGAAAGIABAJIAAAIIABALIAAAMIAAAGIgBAEIAAADIAAAFIABAEIgBAEIAAAEIgCAEIgBADIgDADIgCADIgDADIgDACIgEACIgDABIgEABIgEAAIgEAAg");
	this.shape_1.setTransform(458.4273,370.9979);

	this.instance_2 = new lib.Tween3("synched",0);
	this.instance_2.setTransform(-173.55,56.45);
	this.instance_2._off = true;

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF0000").s().p("EAtMAV5IgIgDIgFgEIgGgHIgCgHIAAgBIgGgDIgEgGIgFgFIgDgGIgDgIIgCgIIgDgIIgCgIIgCgLIgBgLIgBgKIAAgBIgFgHIgFgEIgEgFIgEgGIgDgIIgEgIIgDgIIgBgIIAAgIIAAgIIAAgIIgBgSIgBgDIgHgRQgHgSgCgUIgBgTIgBgWIAAgBIgDgIIgCgEIgEgIIgFgIIgDgHIgCgIIgCgHIgDgHIgCgHQgEgOAAgOIgDgCIgGgFIgFgEIgFgGIgFgFIgCgHIgDgGIgBgIIgBgHIAAgIIgBgCIgDgFIgDgGIgGgIIgDgGIgCgEIgEgGIgFgHIgFgHIgFgIIgDgHIgDgHIgDgGIgCgHIgFgIIgFgIQgIgLgFgLIgDgHIgDgIIgFgFIgHgGIgEgGIgFgCIgFgFIgFgEIgEgGIgDgGIgDgIIgCgIIgFgIIgDgHIgFgIIgDgHIgCgHIgCgIIgEgGIgEgEIgFgJIgFgJIgEgIIgDgJIgDgJIgDgJIgCgGIgCgGIgDgJIgCgJIgGgGIgGgGIgHgHIgEgGIgDgHIgDgIIgFgHIgEgFIgEgHIgDgHIgDgIIgBgIIAAgGIgIgGIgIgHIgQgOQg2gbgwgkQgxgjgygfQgggUghgTQgpgXgiggIgsgqIgVgOQgRgNgOgRIgMgPIgLgPIgFgIIguguIgcgcQgKgKgMgKIgQgNIgLgDIgIgEIgGgEIgIgHIgHgHIgIgGIgFgDIgBgBIgBAAIAAAAIgBgBIgIgCIgKgFIgSgIIgHgEIgGgGQgKgIgMgGIgIgFIgJgDIgKgFIgHgDIgHgEQhVgrhagmQgWgJgWgNQhTgxhWgqQg2gbg4gYQg6gZg6gcQhMgmhSgUIgPgGQgQgIgRgEIgVgHQgIgBgHgDIgOgGIgHgDIgJgHIgBAAQgjgLgegRQgVgMgYgFQgXgHgWgIQgdgLgbgOIgKgFIgKgDIgKgEIgcgJIgJgDIgHgFIgFgEIgEgBIAAgBIAAABIgBgBIgEgCQgTABgRgCQgOAAgNgEIgZgGIgQgDIgQgFIgCAAIgBAAIjggBIi8ABIi5gBQhHAAhGACIABgBIACAAIAAAAIAAAAIgCAAIgCAAIgBABIgBAAIgFACQgVAKgWAEQgNADgPABIgcgBIgSAAIgJAAIAGAEIAFAFIAFAHIAFAHIAEAGIAEAGIAFAGIAFAGIAFAGIAIAPIAEAJIACAKIACAKIAEAHIADAIIAFAHIAEAGIAFAHIADAHIADAJQAEAwgBAxIAABKIAABWQAAAfgCAfIgCAHIgDAHIgDAHIgEAFIgDAFIgCAFIgEAJIgEALIgEAJIgEAGIgFAGIgFAHIgGAFIgFAGIgFAIIgEAHIgFAGIgFAGIgGAFIgIAFQgLAIgLAIIgHAGIgIAEIgIADIgZAJIgRAGIgIADQghAEgjAAIg4AAQgRAAgPgCIgygIQgcgCgbABIggAAIgcAAIgKAAIgJgDIgIgDIgIgGIgHgFIgHgGIgHgGIAAAAIgJgDIgFgBIgIgDIgGgFIgHgFIgGgGIgEgHIgGgEIgFgEIgEgGIgDgHIgEgHQgEgpABgoIABg2IAAg4IAAgvIAAgJIADgKIADgIIADgJIAAgKIABgLQAAgNADgOIAFgKIACgHIALgYIAEgHIAEgHIAFgGIAGgEIAGgGIAFgFIAEgGIAUgZIAGgHIAHgHIAFgHIAFgIIAGgEIAGgEIAHgDIADgDIAEgHIAEgHIAHgGIAHgEIAHgDIAGgCIAHgCIAIgEIAJgFQANgGAPgEIAIgEIAJgEIAYgLIAIgEIAIgDIAIgBIAJgBIAagCIAKgDIAKgCIAogLIAQgEIAGgDIAHgDIAJgCIAJgBIAJgBQgXgWgVgZQgNgRgMgSIgSgaQgNgRgQgPIgNgQIgFgGIgFgDIgJgCIgIgDIgJgCIgHgCIgIgEIgGgEIgGgFIgGgFQgJgJgIgKIgDgFIgFgEIgEgDQhNgdhMgjQhEgehBgnQg5gkg2goQg1gog9ggQgRgKgQgOIgJgDIgNAAQgTAAgSgDIgSgEIgRgDIgJgBIgIgEIgGgEIgGgEIgFgGIgJgBIgIgBIgIgDIgIgDIgHgDIgJgEIgIgDIgagKIgGgEIgFgEIg1gOQgVgEgVgJIgcgMIgSgJIgugOQgRgFgPgKIgVgQIgMgMQgJgIgHgKIAAgBIgIgCIgIgDIgDgCIgBgBIgBAAIgBAAIgCgBQgpgCgpAAIg2ABQgYAAgXgBQgXgDgXgFQgtgCguABIhOAAIhMAAQgbAAgaABIgIACIgIACIgeAFIgGABIgHADIgIADIgFABIgGABIgIABIgIAAIgKAAIgLAAIgKABIgJADIgIACQgMAEgOAAIgJAAIgJABIgJACIgIACIgZADIgIABIgIgBIgJgCIgHgBIgIAFIgIAEIgHADQgMAHgOADIgLACIgLABIgKABIgFAFIgFAFIgGADIgHAEIgHACIgHABIgFAEIgGADIgHACIgHACIgGADIgFAEIgHAGIgGAFIgGAEIgHADIgIACIgIACIAAAAIgJAGIgDAFIgDADIgEAGIgGAEIgFAEIgEADIgCADIgCAHIgEAGIgEAFIgGAEIgGACIgHABIgIgBIgIgDIgGgFIgEgGIgDgHIgCgIIACgIIACgIIADgHIAFgHIAEgGIAGgGIAFgFIAGgFIAHgIIAHgGIAGgEIAKgIIAGgFIAHgDIAHgBIAFgBIABAAIADgCIAFgGIAIgGIAIgEIAJgGIAJgDIAJgEIAGgDIAGgCIAGgCIAGgCIACgCIAEgFIAGgFIAHgEIAGgDIAIgCIAIAAIAJgBIAJAAIAIgCIAIgDIAIgDIADgBIAHgHIAHgEIAGgEIAIgBIAIgBIAHAAIAJABIAGACIAJACIAEAAIAIgCIAJgCIAbgEIAKAAIAJgBIARgFQARgEASAAIASgBIAKAAIAGgCIAHgCIAHgCQAsgKAtgCQApgCAoAAIBWAAIBRAAIAVAAIAKABIAJACIAgAGQAkACAkgBIA5AAIAegBQAVAAAVAEIAGACIAHADQANAEAMAGIAIAFIAHAGIAFAHIAFAHIAJAIIAIAHQAKAIAMAIQAiAIAiAPQATAKAVAHQAYAJAZAFQAXAEAXAJIAHAFIAHAEIAFACIAGADIALADIARAHIAFADIAEAAIAJABIAIABIAJADIAHADIAHAEIAGAFIAFAGIAKACIAKABIAZAEIALABIAMABQAMAAALADIAHABIAHADIAHADIAGAEIAFAFIAIAIIAIAEIAIAGIAVANQBCAfA4AuQA5AvBBAiQA8AhBAAZIB9A1IAHAFIAGAFIAGAHIAFAHIAFAFIAKALIADABIAKACQAMAEAMAFIAIADIAHAGIAHAEQAOARAQAQIAVAYIAQAWIAKAQIAKAQIAMANQAMAPAOANIAMAPIALANIASgCQAXgCAXAAIAeAAIAVAAIAKgCIAKgDIAegMQB7gFB8ABIDYABID9gBQBBgBA9AVIALABIAKAAIAXAAIAIABIAJACIAIAEIAIADIAHAFIAGAEIAUAHQAVAFATAJIATAKIAJADIAKADQAOAFANAGIAJAEIAVAGQAVAGAUAJIAZAMIASAJIAKAFIAJADQAMAEAMAGIAGAEIAHAEIATAGQARADARAHIAOAHIALAEIACABIABAAIgBAAIACABQByAcBoA4QBUAsBZAjQAsARApAaQBpBFB1AqQA4AUAyAhIAHACIAHADIAIAEQAMAHALAHIAGAGIADACIAFADIAEAEIAGACIAUAJIAGADIAJAEIAHAFIAIAGIAHAHIAHAHIALAEIAGACQAWAPAUARIAcAbIAWAWIAdAdIAHAHIAGAHIAEAHIAPAVIAGAHIAGAGIAGAGIAHAGQA2AqA0AtQAVATAaAMQA3AaAuAmQApAiAsAbQAfASAhAQIAGAFIAHAGIATARIAIAGIAHAEIAEAHIAEAGIACAGIACAIIABAHIAAAHIAAAAIAFAGIAEAGIAFAHIACAHIADAGIAHAHIAHAHIAFAGIAFAHIAEAJIADAKIACAJIADAGIACAHIACAJIACAJIAFAHIADAHIAOAWIADAHIADAHIACAIIAGAJIAFAKIADAHIACAGIACAGIAFADIADADIAHAJIAIAIIAHAIIAEAFIAEAGIADAKQAGALAHAMIAFAHIAFAHIAEAHIACAIIAEAIIADAHIACAFIAEAGIAGAIIAGAHIADAIIAAACIAGAGIAGAJIAEAJIAEAHIACAIIABAJIABAJIAGAEIAFAGIAGAEIAEAGIAFAIIACAJIABAKIABAJIACAIIADAIIACAJIADAJIADAEIAEAJIAEAJIADAHIADAJIABAKIACAKIABAfIACAKIADAKIADAKIAEAHIACAIIACAIIACAHQACAMAAANIAAAJIAAAJIAAAEIABABIAFAFIAFAHIAGAFIADAFIAEAHIACAHIABAHIABAHIABAMIAAAKIABAEIACAEIADAFIACAGIAEADIAEAEIAFAFIAEAHIACAHIABAIIABAIIAAAHIgDAHIgFAHIgGAEIgHADIgIABIgIgBgEAtTAUcIABACIAAgCIgBgBIAAABgArxAKIArAGQASADAUgBIALAAIAPAAIAQAAIASAAIARAAIARAAIALgBIAFgCIAFgBIAFgDIAEgCIAGgBIAEgCIAFgBIAEgCIAFgCIAEgBIAFgBIABgBIABAAIAAgBIABgBIAAgBIABAAIAEgDIAEgDIAEgEIAFgDIAEgCIAFgDIACgEIADgGIADgEIADgGIACgDIAEgDIACgEIADgCIAEgEIADgDIACgEIAEgEIACgEIABgGIACgEIACgFIACgEIACgFIACgGIAEgEIACgEIACgEIABgxIgBg2IAAg+IABhBQABgfgCgfIgGgLQgFgFgDgHIgFgJIgEgJIgEgKIgCgJIgCgLIgDgFIgEgDIgCgEIgEgEIgDgDIgCgFIgEgEIgDgFIgCgEIgEgFIgCgCIgFgEIgFgDIgEgDIgEgEIgDgDIgEgDIgDgDIgDgDIgFABIgEACIgFACIgFACIgFABIgGAAIgEABIgFAAIgEAAIgGAAIgBAAIgCACIgEABIgEADIgGABQgJABgKADIgUAHIgUAFIgVAFQgKACgLgBIgMABIABgBIACAAIAAAAIAAAAIgCAAIgCAAIgBABIgBAAIgIAEIgKADIgJAFIgIAEIgIAEIgJAEIgJADIgJADIgFADIgEABIgEACIgEADIgFACIgEABIgFACIgEACIgFACIgBADIgDAEIgEAEIgDAEIgFAEIgDADIgFADIgEACIgDACIgEAEIgDAFIgDADIgEAFIgDADIgEAFIgDADIgDAEIgEAFIgCAEIgEAFIgEAEIgCAEIgDADIgEAEIgCADIgEADIgEADIgDADIgDAEIgCAFIgCAEIgCAFIgDAEIgCAFIgBAEIgBAEIgCAFIgBAGIAAAEIAAgDIABgDIAAAFIAAAGIgBAGIAAAGIgBAFIgBAHIgBAEIgBAFIgCAEIgBAFIgBAEIgBAFIAAAvIAAAoIAAAvIgCAtQgBAWAGATIACACIADADIADADIACADIADADIAFACIAEAAIAFACIADABIAFADIAEADIAEADIAEAEIAFACIAEADIAEAEQAVACAVgBIAlAAIAIAAQARAAASACgArJn7IgCAAIADAAIABgCIgCACgAIdo6IgBgBIgBAAIACABgAIZo8IACAAIAAAAIgBAAIgBgBIgBAAgA01xnIABAAIABABIgBgBIgBgBIgBAAgA08xrIABAAIABABIgBgBIgBgBIgBAAgEgsUgUBIgBABIgBAAIACAAIABgBIgBAAgEgrJgUoIABgBIABAAIAAAAIgCABgEgnEgUpIABAAIACAAIgCAAIgBAAg");
	this.shape_2.setTransform(260.95,214.25);

	this.instance_3 = new lib.Tween4("synched",0);
	this.instance_3.setTransform(430.4,393.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.instance_1}]}).to({state:[{t:this.shape_2},{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},4).to({state:[{t:this.instance_3}]},24).wait(61));
	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({_off:false},0).wait(4).to({x:491.7,y:398.6},0).to({_off:true,x:430.4,y:393.5},24).wait(61));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-97.1,234.5,1150,376.6);
// library properties:
lib.properties = {
	id: '4EEF7980F346FC45847A1B565642FB9F',
	width: 640,
	height: 480,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['4EEF7980F346FC45847A1B565642FB9F'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;